#!/bin/bash

## Description: Run npx inside the web container for the nuxt frontend.
## Usage: npx [flags] [args]
## Example: "ddev npx playwright install"
## HostWorkingDir: true

cd /var/www/html/frontend; npx "$@"
